name: Deploy to host via SFTP
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}   # en clair (pas base64)
          port: 22
          sftp_only: true
          local_path: "./"
          remote_path: "/clickandbuilds/MaisonMelina/"
          # options utiles (facultatif)
          sftpArgs: "-o StrictHostKeyChecking=no -o ConnectTimeout=30"
          delete_remote_files: false
