name: Deploy PREPROD (IONOS)
on:
  push:
    branches: [ preprod ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ajoute robots.txt (noindex) et un .htaccess minimal côté préprod
      - name: Prepare PREPROD headers
        run: |
          echo -e "User-agent: *\nDisallow: /" > robots.txt
          cat > .htaccess <<'EOF'
          DirectoryIndex index.html index.htm
          RewriteEngine On
          RewriteCond %{HTTPS} !=on
          RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
          <IfModule mod_headers.c>
            Header set X-Robots-Tag "noindex, nofollow, noarchive"
          </IfModule>
          EOF

      # Déploiement SFTP vers IONOS (sans 'exclude')
      - name: Deploy via SFTP to IONOS
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.IONOS_HOST }}      # ex: access935993939.webspace-data.io
          username: ${{ secrets.IONOS_USER }}    # ex: u109679466
          password: ${{ secrets.IONOS_PASS }}    # ton mot de passe SFTP
          port: ${{ secrets.IONOS_PORT || 22 }}
          sftp_only: true
          # Optionnel si warning de clé d'hôte:
          # sftpArgs: "-o StrictHostKeyChecking=no"
          local_path: '.'
          remote_path: '/www/preprod-melina/'
